services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: et
      POSTGRES_PASSWORD: et
      POSTGRES_DB: et
    ports:
      - "5433:5432"
    volumes:
      - et_db:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - et_minio:/data

volumes:
  et_db:
  et_minio:
